apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathsargocd-app
  labels:
    app: mathsargocd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mathsargocd-app
  template:
    metadata:
      labels:
        app: mathsargocd-app
    spec:
      containers:
        - name: mathsargocd-app
          image: a-justin/maths-deploy 
          ports:
            - containerPort: 8000
